name: Build Standalone App

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    
    env:
      baseDir: ./CompileScore/WPF
      solutionName: CompileScoreWPF.sln
    
    strategy:
      matrix:
        buildconfig: [Debug, Release]
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1
     
    - uses: nuget/setup-nuget@v1
      with:
        nuget-version: '5.x'
        
    - name: NuGet restore ${{ env.solutionName }}
      working-directory: ${{env.baseDir}}
      run: nuget restore ${{ env.solutionName }}
     
    - name: Build Score Data Extractor
      working-directory: ${{env.baseDir}}
      run: msbuild /m /p:Configuration=${{matrix.buildconfig}} ${{ env.solutionName }}
      
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: CompileScore-App-${{matrix.buildconfig}}
        path: ${{env.baseDir}}/bin/${{matrix.buildconfig}}/*
